server:
  port: 8080
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.google.com
file:
  upload-dir: /web/java/upload-dir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
email:
  subject: "Default Subject"
  message: "Default Message"
spring:
  application:
    name: springboot-java-rest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://maus-db-server.c4x0siiiaxul.us-east-1.rds.amazonaws.com/springboot_java_rest?useTimezone=true&serverTimezone=UTC
    username: root
    password: pkI&^gZ5Gd%AxL0F #for tests only
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false #spring.jpa.open-in-view
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    root: INFO #globally
    #net.sf.jasperreports.engine.*: TRACE
    #br.com.maus: DEBUG #by package
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
